title: Yegair.io
email: hauke.jaeger@yegair.io
baseurl: ""
url: "http://yegair.io"
github_username:  yegair

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
