title: Yegair.io
email: hauke.jaeger@yegair.io
baseurl: ""
url: "http://yegair.io"
github_username:  yegair
repository: Yegair/yegair.github.io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
